POST http://127.0.0.1:8080/equipment
Content-Type: application/json

{
  "name": "name2",
  "equipmentType": "type1",
  "manufacturer": "man1",
  "model": "model1",
  "serialNumber": "serial1",
  "location": "loc1",
  "dateInstalled": {
    "year": 2023,
    "month": 3,
    "day": 19
  },
  "lastMaintenanceDate": {
    "year": 2023,
    "month": 3,
    "day": 20
  }
}

###
GET http://127.0.0.1:8080/equipment
Accept: application/json

###
GET http://127.0.0.1:8080/equipment/1
Accept: application/json

###
GET http://127.0.0.1:8080/equipment/2
Accept: application/json

###
DELETE http://127.0.0.1:8080/equipment/2
